CREATE TABLE [dbo].[bas_TaokeSale] (
    [ID]             BIGINT          IDENTITY (1, 1) NOT NULL,
    [NumIID]         BIGINT          NOT NULL,
    [Title]          VARCHAR (500)   NOT NULL,
    [UserID]         TINYINT         CONSTRAINT [DF_bas_TaokeSale_User] DEFAULT ((1)) NOT NULL,
    [ClickTime]      BIGINT          NOT NULL,
    [CreateTime]     BIGINT          NOT NULL,
    [AccountTime]    BIGINT          NOT NULL,
    [UpdataTime]     BIGINT          CONSTRAINT [DF_bas_TaokeSale_UpdataTime] DEFAULT ((1508827125)) NOT NULL,
    [AccountMoney]   DECIMAL (18, 2) NOT NULL,
    [CommissionRate] DECIMAL (18, 2) NOT NULL,
    [Commission]     DECIMAL (18, 2) NOT NULL,
    [PayMoney]       DECIMAL (18, 2) NOT NULL,
    [OrderID]        BIGINT          NOT NULL,
    [OrderStatus]    TINYINT         NOT NULL,
    [AdzoneID]       BIGINT          NOT NULL,
    [SiteID]         BIGINT          NOT NULL,
    [CatTitle]       VARCHAR (500)   NOT NULL,
    [Nick]           VARCHAR (500)   NOT NULL,
    [ShopName]       VARCHAR (500)   NOT NULL,
    [DealPlatform]   VARCHAR (500)   NOT NULL,
    [SaleCount]      INT             NOT NULL,
    [SalePrice]      DECIMAL (18, 2) NOT NULL,
    [OrderType]      VARCHAR (500)   NOT NULL,
    [IncomeRate]     DECIMAL (18, 2) NOT NULL,
    [PartRate]       DECIMAL (18, 2) NOT NULL,
    [EffectEst]      DECIMAL (18, 2) NOT NULL,
    [EffectIncome]   DECIMAL (18, 2) NOT NULL,
    [SubsidyRage]    DECIMAL (18, 2) NOT NULL,
    [SubsidyMoney]   DECIMAL (18, 2) NOT NULL,
    [SubsidyType]    VARCHAR (500)   NOT NULL,
    [ThirdSouce]     VARCHAR (500)   NOT NULL,
    [SiteName]       VARCHAR (500)   NOT NULL,
    [AdzoneName]     VARCHAR (500)   NOT NULL,
    CONSTRAINT [PK_bas_TaokeSale] PRIMARY KEY CLUSTERED ([ID] ASC)
);

