CREATE TABLE [dbo].[Web_ItemWeb] (
    [ID]  INT    IDENTITY (1, 1) NOT NULL,
    [WID] INT    NOT NULL,
    [IID] BIGINT NOT NULL,
    CONSTRAINT [PK_Web_ItemWeb] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_Web_ItemWeb]
    ON [dbo].[Web_ItemWeb]([IID] ASC, [WID] ASC);

